Assistant checkpoint: Added missing VisualizationConfig class definition
Assistant generated file changes:
- src/tree_visualizer/config.py: Add VisualizationConfig class

---

User prompt:

Traceback (most recent call last):
  File "/home/runner/Tree/main.py", line 11, in <module>
    from src.tree_interval import Tree, Leaf, Position, TreeVisualizer, VisualizationConfig, AstTreeBuilder
  File "/home/runner/Tree/src/tree_interval/__init__.py", line 10, in <module>
    from src.tree_visualizer import TreeVisualizer, VisualizationConfig
  File "/home/runner/Tree/src/tree_visualizer/__init__.py", line 8, in <module>
    from .config import VisualizationConfig
ImportError: cannot import name 'VisualizationConfig' from 'src.tree_visualizer.config' (/home/runner/Tree/src/tree_visualizer/config.py)